### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by firasdib** [firasdib/regex101-translations#14]
I have a one year free coupon for Transifex, is this something that would be beneficial for the project to move to?

**Comment by working-name** [comment]
I believe it would make translation easier, and more accessible.

There's also [poeditor](https://poeditor.com/pricing/) which is free if under 1,000 strings, and can handle JSON. Unlimited languages, contributors.

**Comment by OnlineCop** [comment]
- Will it cost you anything out-of-pocket?
- Will you be able to use them for the entire project, or will it be piecemeal?
- Is it better to have portions of the site translated and others left in English, rather than to have nothing translated at all?
- Do they have any terms that indicate that you must credit them on the site somewhere, or have some restrictions ("the translations belong to Transifex, and you may not continue to use them after your 'free year' expires") that would give you pause?

**Comment by TWiStErRob** [comment]
I think you'll always have partially translated website as long as you use crowd translation. And I don't think you want to be blocked on translators every time you change a string. Even if this repo is used (in contrast to a translation service) there will be missing translations if the site keeps evolving.

I think @OnlineCop's last question is an important one, thought it would be hard to believe that they would own the translations.

**Comment by firasdib** [comment]
Transifex is up and running. Please send me your email addresses and I'll invite you.

**Comment by working-name** [comment]
Hey guys, just a quick update:

Transifex had some trouble while importing the JSON strings and we had to move on to something else.

There's a weblate instance up and running at [https://r101.cf](https://r101.cf). You can use your existing github or google account to log in. Rest assured, your private info stays that way. 

This is a collaborative translation platform, and even if you don't want to create an account you can still suggest translations.

If you would like to translate to another language, just log in add it!
