### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by julmot** [firasdib/regex101-translations#2]
I think "Your have not created anything yourself yet." should be "You have not created anything yourself yet."

Btw: I think it would make sense to not include punctuation marks inside translations, in this case the `.` at the end.

**Comment by firasdib** [comment]
You're right, typo by me.

I'm not quite sure how to handle the punctuations, it might not fit to append a question mark always or something along those lines.

**Comment by julmot** [comment]
I'm not familiar with any language, where a `?` or `.` isn't always at the end of a sentence. If there are multiple sentences within one translation, that of course they'll have to be included.

**Comment by firasdib** [comment]
Perhaps spanish, where you need to add the inverted question mark to the front. Might look odd having only it in the front for those translations. Nevertheless I'm not sure its that big of an issue, do you? Are you afraid of accidental deletion of punctuations?

**Comment by julmot** [comment]
Let's wait for someone speaking Spanish as I'm not familiar with it.

**Comment by working-name** [comment]
I'm no expert, nor am I one to appreciate formal language in UIs, but the `¿` and `¡` are normally expected (it's proper grammar) in texts that are a little more formal than your regular tweet or text message.

However, it can get complicated due to the fact that a question is not always considered to be the full sentence.

Here's a few examples:
`¿Quieres eliminar este expression regular?` = Do you want to delete this regex?
`Hola, ¿como estas?` = Hi, how are you?
`Muy bien entonces, ¡gracias!` = Very well then, thank you!

**Comment by firasdib** [comment]
@working-name In that case perhaps it makes more sense to leave the punctuations in the translation sentence?

**Comment by working-name** [comment]
Yes, I think so.
